---
# yamllint disable rule:truthy
# yamllint disable rule:line-length
- name: Switch config
  connection: network_cli
  hosts: switch.com
  gather_facts: no
  become: yes
  become_method: enable
  tasks:
    - name: IOS >> VLAN Updates
      ios_vlan:
        aggregate: 
          - { 'vlan_id': 2, 'name': 'TRANSIT', state: present }
          - { 'vlan_id': 5, 'name': 'Test VLAN', state: absent }
      register: command_output

    - name: DEBUG >> VLAN Update
      debug:
        msg: "{{ command_output }}"
