---
- 
  name: Configure SNMP Contact 
  hosts: "nexus"
  gather_facts: false 
  connection: local

  vars:
   cli:
    host: "{{ inventory_hostname }}" 
    username: admin
    password: root@123 
    transport: cli

  tasks:
    - name: configure snmp contact 
     
      nxos_snmp_contact:
       contact: TEST_1 
       state: present 
       provider: "{{ cli }}"

      register: output

    - name: show output 
      debug:
       var: output

